title: Defiance Home for Sale
description: 'Home for sale in Defiance Missouri'

baseurl: 'https://defiancehome.com'

copyright: Copyright Â© 2024 Kampfire Technologies

enablerobotstxt: true
languagecode: en-us
timezone: America/Chicago
timeout: 60000s

module:
  imports:
    - path: github.com/gethinode/hinode
    - path: github.com/gethinode/mod-bootstrap
    - path: github.com/gethinode/mod-fontawesome
    - path: github.com/gethinode/mod-leaflet

deployment:
  targets:
    - name: production
      URL: s3://defiancehome-com?region=us-east-1
      cloudFrontDistributionID:	E27WOJ1ENY5GKJ